import type { CommitData, DetectionSignal } from "../types";

const COAUTHOR_PATTERNS = [
  /Co-authored-by:\s*.*Copilot/i,
  /Co-authored-by:\s*.*\[bot\]/i,
  /Co-authored-by:\s*.*Claude/i,
  /Co-authored-by:\s*.*Cursor/i,
];

const GENERATED_PATTERNS = [
  /generated by/i,
  /auto-generated/i,
  /AI generated/i,
];

export function checkCopilotCoauthor(
  commit: CommitData,
  weight: number
): DetectionSignal {
  for (const pattern of COAUTHOR_PATTERNS) {
    const match = pattern.exec(commit.message);
    if (match) {
      return {
        name: "copilot_coauthor",
        weight,
        matched: true,
        detail: `Found: "${match[0]}"`,
      };
    }
  }

  for (const pattern of GENERATED_PATTERNS) {
    if (pattern.test(commit.message)) {
      return {
        name: "copilot_coauthor",
        weight: weight * 0.8,
        matched: true,
        detail: "Commit message mentions generation",
      };
    }
  }

  return { name: "copilot_coauthor", weight: 0, matched: false };
}
